service:
  name: serverless-udagram-app

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    GROUPS_TABLE: Groups-${self:provider.stage}
    IMAGES_TABLE: Images-${self:provider.stage}
    IMAGE_ID_INDEX: ImageIdIndex
    IMAGES_S3_BUCKET: serverless-udagram-${self:provider.stage}
    SIGNED_URL_EXPIRATION: 300

  # 사용자가 명령어를 실행할 때 전달한 stage 라는 옵션이 있다면
  # 이를 사용하고 없다면 dev 를 사용한다.
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        # groupId로 한 group의 이미지들 쿼리할 수 있는 권한
        - dynamodb:GetItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.GROUPS_TABLE}
    # Query 하기 위한 권한 추가
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.IMAGES_TABLE}

    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.IMAGES_TABLE}/index/${self:provider.environment.IMAGE_ID_INDEX}

    # 람다함수가 S3에 업로드를 할 수 있도록하고 presignedUrl을 생성할 수 있도록 권한 추가
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: arn:aws:s3:::${self:provider.environment.IMAGES_S3_BUCKET}/*

functions:
  GetGroups:
    handler: src/lambda/http/getGroups.handler
    #connect function to event source
    events:
      - http:
          method: get
          path: groups
          cors: true

  CreateGroups:
    handler: src/lambda/http/createGroups.handler
    events:
      - http:
          method: post
          path: groups
          cors: true
          reqValidatorName: RequestBodyValidator
          request:
            schema:
              application/json: ${file(models/create-groups-request.json)}
          documentation:
            summary: Create a new group
            description: Create a new group

  GetImages:
    handler: src/lambda/http/getImages.handler
    events:
      - http:
          method: get
          path: groups/{groupId}/images
          cors: true

  GetImage:
    handler: src/lambda/http/getImage.handler
    events:
      - http:
          method: get
          path: images/{imageId}
          cors: true

  CreateImage:
    handler: src/lambda/http/createImage.handler
    events:
      - http:
          method: post
          path: groups/{groupId}/images
          cors: true
          reqValidatorName: RequestBodyValidator
          request:
            schema:
              application/json: ${file(models/create-image-request.json)}
          documentation:
            summary: Create a new image
            description: Create a new image

  SendUploadNotifications:
    handler: src/lambda/s3/sendNotifications.handler

resources:
  Resources:
    # API 게이트웨이에서 요청 검증을 하기 위한 요청 body 검증 리소스 추가
    RequestBodyValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: 'request-body-validator'
        RestApiId:
          Ref: ApiGatewayRestApi
        #요청 body만 검증하고 파라미터는 검증하지 않는다.
        ValidateRequestBody: true
        ValidateRequestParameters: false

    GroupsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.GROUPS_TABLE}

    ImagesDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: groupId
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
          - AttributeName: imageId
            AttributeType: S
        KeySchema:
          - AttributeName: groupId
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.IMAGE_ID_INDEX}
            KeySchema:
              - AttributeName: imageId
                KeyType: HASH
            # 기존 테이블 데이터의 어떤 속성들을 GSI의 결과로 생성되는 테이블에 복사할지
            # 지정하는 부분. 여기서는 모든 속성들을 복사
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.IMAGES_TABLE}

    # 어플리케이션에 S3 버켓으로 요청을 보냈을 때 S3 버켓이
    # cors 헤더를 알맞게 추가할 수 있도록 관련 설정들 추가
    AttachmentsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.IMAGES_S3_BUCKET}
        # S3 버켓으로 부터 발생한 이벤트를 람다함수와 연결하기 위한 설정
        NotificationConfiguration:
          LambdaConfigurations:
            - Event: s3:ObjectCreated:*
              #이벤트 발생시 호출할 람다함수
              #CloudFormation의 GetAttribute 함수를 사용하여
              #SendUploadNotificationsLambdaFunction 함수로부터 Arn을 얻어온다. ?
              Function: !GetAtt SendUploadNotificationsLambdaFunction.Arn
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000

    # 람다함수를 호출할 수 있는 람다권한 추가
    SendUploadNotificationsPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: !Ref SendUploadNotificationsLambdaFunction
        #s3만 이 함수를 호출할 수 있음
        Principal: s3.amazonaws.com
        Action: lambda:InvokeFunction
        #s3 버켓의 소유자 계정Id
        SourceAccount: !Ref AWS::AccountId
        #s3 버켓중에서도 이 버켓만 이 함수를 호출할 수 있음
        SourceArn: arn:aws:s3:::${self:provider.environment.IMAGES_S3_BUCKET}

    # 모든 사용자가 이 버켓에서 이미지를 읽을 수 있도록 정책 추가
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: MyPolicy
          Version: '2012-10-17'
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: 'arn:aws:s3:::${self:provider.environment.IMAGES_S3_BUCKET}/*'
        # 어떤 S3 버켓에 이 정책을 추가할지 지정
        Bucket: !Ref AttachmentsBucket
